In [142]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [143]:
data=load_iris()
x=data.data
y=data.target
d_names=data.target_names

In [144]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=1)

In [145]:
def predict_one(x_train,y_train,x,k):
    dist={}
    for i in range(len(x_train)):
        cd=(((x-x_train[i])**2).sum())**(1/2)
        dist[cd]=y_train[i]
        sorted_dist=sorted(dist.items())
        target=[]
        dist_sort=sorted_dist[:k]
        for key,v in dist_sort:
            target.append(v)      
    return max(set(target),key = target.count)    

In [146]:
def predcit(x_train,y_train,x_test,k):
    predictions=[]
    for x in x_test:
        predictions.append(predict_one(x_train,y_train,x,k))
    return predictions    

In [147]:
y_pred=predcit(x_train,y_train,x_test,3)

In [148]:
y_pred_train=predcit(x_train,y_train,x_train,3)

In [149]:
print("Training Accuracy",accuracy_score(y_train,y_pred_train))

Training Accuracy 0.9733333333333334


In [150]:
print("Testing Accuracy",accuracy_score(y_test,y_pred))

Testing Accuracy 0.92


In [151]:
print(confusion_matrix(y_test,y_pred))

[[24  0  0]
 [ 0 24  0]
 [ 0  6 21]]


In [152]:
for i in range(len(y_test)):
    print(f'Predicted-:{y_pred[i]} Predicted Label-:{d_names[y_pred[i]]} Original Label-:{d_names[y_test[i]]}')

Predicted-:0 Predicted Label-:setosa Original Label-:setosa
Predicted-:1 Predicted Label-:versicolor Original Label-:versicolor
Predicted-:1 Predicted Label-:versicolor Original Label-:versicolor
Predicted-:0 Predicted Label-:setosa Original Label-:setosa
Predicted-:2 Predicted Label-:virginica Original Label-:virginica
Predicted-:1 Predicted Label-:versicolor Original Label-:versicolor
Predicted-:2 Predicted Label-:virginica Original Label-:virginica
Predicted-:0 Predicted Label-:setosa Original Label-:setosa
Predicted-:0 Predicted Label-:setosa Original Label-:setosa
Predicted-:2 Predicted Label-:virginica Original Label-:virginica
Predicted-:1 Predicted Label-:versicolor Original Label-:versicolor
Predicted-:0 Predicted Label-:setosa Original Label-:setosa
Predicted-:2 Predicted Label-:virginica Original Label-:virginica
Predicted-:1 Predicted Label-:versicolor Original Label-:versicolor
Predicted-:1 Predicted Label-:versicolor Original Label-:versicolor
Predicted-:0 Predicted Label

In [153]:
correct=[]
incorrect=[]
predic=[]
trueCount=0
falseCount=0
for i in range(len(y_test)):
    if y_pred[i]==y_test[i]:
        correct.append((x_test[i],y_pred[i],d_names[y_pred[i]],True))
        predic.append((x_test[i],y_pred[i],d_names[y_pred[i]],True))
        trueCount=trueCount+1
    else:
        incorrect.append((x_test[i],y_pred[i],y_test[i],d_names[y_pred[i]],d_names[y_test[i]],False))
        predic.append((x_test[i],y_pred[i],d_names[y_pred[i]],False))
        falseCount=falseCount+1

In [154]:
predic

[(array([5.8, 4. , 1.2, 0.2]), 0, 'setosa', True),
 (array([5.1, 2.5, 3. , 1.1]), 1, 'versicolor', True),
 (array([6.6, 3. , 4.4, 1.4]), 1, 'versicolor', True),
 (array([5.4, 3.9, 1.3, 0.4]), 0, 'setosa', True),
 (array([7.9, 3.8, 6.4, 2. ]), 2, 'virginica', True),
 (array([6.3, 3.3, 4.7, 1.6]), 1, 'versicolor', True),
 (array([6.9, 3.1, 5.1, 2.3]), 2, 'virginica', True),
 (array([5.1, 3.8, 1.9, 0.4]), 0, 'setosa', True),
 (array([4.7, 3.2, 1.6, 0.2]), 0, 'setosa', True),
 (array([6.9, 3.2, 5.7, 2.3]), 2, 'virginica', True),
 (array([5.6, 2.7, 4.2, 1.3]), 1, 'versicolor', True),
 (array([5.4, 3.9, 1.7, 0.4]), 0, 'setosa', True),
 (array([7.1, 3. , 5.9, 2.1]), 2, 'virginica', True),
 (array([6.4, 3.2, 4.5, 1.5]), 1, 'versicolor', True),
 (array([6. , 2.9, 4.5, 1.5]), 1, 'versicolor', True),
 (array([4.4, 3.2, 1.3, 0.2]), 0, 'setosa', True),
 (array([5.8, 2.6, 4. , 1.2]), 1, 'versicolor', True),
 (array([5.6, 3. , 4.5, 1.5]), 1, 'versicolor', True),
 (array([5.4, 3.4, 1.5, 0.4]), 0, 'set

In [155]:
print("Correct Predicted",trueCount)
print("incorrect Predicted",falseCount)

Correct Predicted 69
incorrect Predicted 6


In [156]:
print("Correct Predictions-:")
correct


Correct Predictions-:


[(array([5.8, 4. , 1.2, 0.2]), 0, 'setosa', True),
 (array([5.1, 2.5, 3. , 1.1]), 1, 'versicolor', True),
 (array([6.6, 3. , 4.4, 1.4]), 1, 'versicolor', True),
 (array([5.4, 3.9, 1.3, 0.4]), 0, 'setosa', True),
 (array([7.9, 3.8, 6.4, 2. ]), 2, 'virginica', True),
 (array([6.3, 3.3, 4.7, 1.6]), 1, 'versicolor', True),
 (array([6.9, 3.1, 5.1, 2.3]), 2, 'virginica', True),
 (array([5.1, 3.8, 1.9, 0.4]), 0, 'setosa', True),
 (array([4.7, 3.2, 1.6, 0.2]), 0, 'setosa', True),
 (array([6.9, 3.2, 5.7, 2.3]), 2, 'virginica', True),
 (array([5.6, 2.7, 4.2, 1.3]), 1, 'versicolor', True),
 (array([5.4, 3.9, 1.7, 0.4]), 0, 'setosa', True),
 (array([7.1, 3. , 5.9, 2.1]), 2, 'virginica', True),
 (array([6.4, 3.2, 4.5, 1.5]), 1, 'versicolor', True),
 (array([6. , 2.9, 4.5, 1.5]), 1, 'versicolor', True),
 (array([4.4, 3.2, 1.3, 0.2]), 0, 'setosa', True),
 (array([5.8, 2.6, 4. , 1.2]), 1, 'versicolor', True),
 (array([5.6, 3. , 4.5, 1.5]), 1, 'versicolor', True),
 (array([5.4, 3.4, 1.5, 0.4]), 0, 'set

In [157]:
print("In Correct Predictions-:")
incorrect

In Correct Predictions-:


[(array([6.3, 2.5, 5. , 1.9]), 1, 2, 'versicolor', 'virginica', False),
 (array([6. , 2.2, 5. , 1.5]), 1, 2, 'versicolor', 'virginica', False),
 (array([6.2, 2.8, 4.8, 1.8]), 1, 2, 'versicolor', 'virginica', False),
 (array([6.3, 2.7, 4.9, 1.8]), 1, 2, 'versicolor', 'virginica', False),
 (array([6.1, 3. , 4.9, 1.8]), 1, 2, 'versicolor', 'virginica', False),
 (array([6. , 3. , 4.8, 1.8]), 1, 2, 'versicolor', 'virginica', False)]