In [9]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [10]:
data=load_iris()
x=data.data
y=data.target
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [12]:
def predict_one(x_train,y_train,x,k):
    dist={}
    for i in range(len(x_train)):
        cd=(((x-x_train[i])**2).sum())**(1/2)
        dist[cd]=y_train[i]
        sorted_dist=sorted(dist.items())
        target=[]
        dist_sort=sorted_dist[:k]
        for key,v in dist_sort:
            target.append(v)      
    return max(set(target),key = target.count)    

In [13]:
def predcit(x_train,y_train,x_test,k):
    predictions=[]
    for x in x_test:
        predictions.append(predict_one(x_train,y_train,x,k))
    return predictions    

In [36]:
y_pred=predcit(x_train,y_train,x_test,3)

In [28]:
y_pred_train=predcit(x_train,y_train,x_train,3)

In [40]:
print("Training Accuracy",accuracy_score(y_train,y_pred_train))

Training Accuracy 0.9523809523809523


In [42]:
print("Testing Accuracy",accuracy_score(y_test,y_pred))

Testing Accuracy 0.9777777777777777


In [18]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 18  0]
 [ 0  1 12]]


In [37]:
correct=[]
incorrect=[]
for i in range(len(y_test)):
    if y_pred[i]==y_test[i]:
        correct.append((x_test[i],y_pred[i]))
    else:
        incorrect.append((x_test[i],y_pred[i],y_test[i]))

In [38]:
print("Correct Predictions-:")
correct

Correct Predictions-:


[(array([5.8, 4. , 1.2, 0.2]), 0),
 (array([5.1, 2.5, 3. , 1.1]), 1),
 (array([6.6, 3. , 4.4, 1.4]), 1),
 (array([5.4, 3.9, 1.3, 0.4]), 0),
 (array([7.9, 3.8, 6.4, 2. ]), 2),
 (array([6.3, 3.3, 4.7, 1.6]), 1),
 (array([6.9, 3.1, 5.1, 2.3]), 2),
 (array([5.1, 3.8, 1.9, 0.4]), 0),
 (array([4.7, 3.2, 1.6, 0.2]), 0),
 (array([6.9, 3.2, 5.7, 2.3]), 2),
 (array([5.6, 2.7, 4.2, 1.3]), 1),
 (array([5.4, 3.9, 1.7, 0.4]), 0),
 (array([7.1, 3. , 5.9, 2.1]), 2),
 (array([6.4, 3.2, 4.5, 1.5]), 1),
 (array([6. , 2.9, 4.5, 1.5]), 1),
 (array([4.4, 3.2, 1.3, 0.2]), 0),
 (array([5.8, 2.6, 4. , 1.2]), 1),
 (array([5.6, 3. , 4.5, 1.5]), 1),
 (array([5.4, 3.4, 1.5, 0.4]), 0),
 (array([5. , 3.2, 1.2, 0.2]), 0),
 (array([5.5, 2.6, 4.4, 1.2]), 1),
 (array([5.4, 3. , 4.5, 1.5]), 1),
 (array([6.7, 3. , 5. , 1.7]), 1),
 (array([5. , 3.5, 1.3, 0.3]), 0),
 (array([7.2, 3.2, 6. , 1.8]), 2),
 (array([5.7, 2.8, 4.1, 1.3]), 1),
 (array([5.5, 4.2, 1.4, 0.2]), 0),
 (array([5.1, 3.8, 1.5, 0.3]), 0),
 (array([6.1, 2.8, 4

In [39]:
print("In Correct Predictions-:")
incorrect

In Correct Predictions-:


[(array([6. , 2.2, 5. , 1.5]), 1, 2)]