In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.datasets import load_iris,load_diabetes

In [2]:
weather=["Sunny","Sunny","Overcast","Rainy","Rainy","Rainy","Overcast","Sunny","Sunny","Rainy","Sunny","Overcast","Overcast","Rainy"]
temp=["Hot","Hot","Hot","Mild","Cool","Cool","Cool","Mild","Cool","Mild","Mild","Mild","Hot","Mild"]
play=["No","No","Yes","Yes","Yes","No","Yes","No","Yes","Yes","Yes","Yes","Yes","No"]

In [3]:
le=LabelEncoder()

In [4]:
w_enc=le.fit_transform(weather)
t_enc=le.fit_transform(temp)
p_enc=le.fit_transform(play)

In [5]:
# x_np=np.array([w_enc,t_enc])
# x=x_np.transpose()
# y=np.array([p_enc])

In [6]:
# x_train,x_test,y_train,y_test=train_test_split(x,p_enc,test_size=0.3,random_state=1)

In [7]:
# clf=DecisionTreeClassifier(criterion="log_loss")
# clf.fit(x_train,y_train)

In [8]:
# y_pred=clf.predict(x_test)
# y_pred

In [9]:
# accuracy_score(y_test,y_pred)

In [10]:
# print(confusion_matrix(y_test,y_pred))

**Classification-:iris**

In [32]:
data=load_iris()
x=data.data
y=data.target
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [33]:
x_test

array([[5.8, 4. , 1.2, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [6.6, 3. , 4.4, 1.4],
       [5.4, 3.9, 1.3, 0.4],
       [7.9, 3.8, 6.4, 2. ],
       [6.3, 3.3, 4.7, 1.6],
       [6.9, 3.1, 5.1, 2.3],
       [5.1, 3.8, 1.9, 0.4],
       [4.7, 3.2, 1.6, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [7.1, 3. , 5.9, 2.1],
       [6.4, 3.2, 4.5, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [4.4, 3.2, 1.3, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3.4, 1.5, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [5.4, 3. , 4.5, 1.5],
       [6.7, 3. , 5. , 1.7],
       [5. , 3.5, 1.3, 0.3],
       [7.2, 3.2, 6. , 1.8],
       [5.7, 2.8, 4.1, 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [6.1, 2.8, 4.7, 1.2],
       [6.3, 2.5, 5. , 1.9],
       [6.1, 3. , 4.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [5.6, 2.5, 3.9, 1.1],
       [6.4, 2.8, 5.6, 2.1],
       [5.8, 2

In [14]:
clf=DecisionTreeClassifier(criterion="entropy")
clf.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [15]:
y_pred=clf.predict(x_test)

In [38]:
d=np.array([5.5, 4.0 , 1.1, 0.2]).reshape(1,-1)
pred=clf.predict(d)
pred

array([0])

In [16]:
accuracy_score(y_test,y_pred)

0.9555555555555556

In [17]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


**As a regressor for diabetes**

In [18]:
d=load_diabetes()
x1=d.data
y1=d.target

In [19]:
x_train_1,x_test_1,y_train_1,y_test_1=train_test_split(x1,y1,test_size=0.3,random_state=1)

In [20]:
x_train_1.shape

(309, 10)

In [21]:
reg=DecisionTreeRegressor()
reg.fit(x_train_1,y_train_1)

DecisionTreeRegressor()

In [25]:
x_test_1.shape

(133, 10)

In [24]:
y_pred_1=reg.predict(x_test_1)

In [23]:
reg.score(x_test_1,y_pred_1)

1.0

In [44]:
x1[:,9]

array([-0.01764613, -0.09220405, -0.02593034, -0.00936191, -0.04664087,
       -0.09634616, -0.03835666,  0.00306441,  0.01134862, -0.01350402,
       -0.03421455, -0.05906719, -0.04249877, -0.01350402, -0.07563562,
       -0.04249877,  0.02791705, -0.0010777 , -0.01764613, -0.05492509,
        0.01549073, -0.01764613, -0.01350402,  0.13561183, -0.05492509,
       -0.03421455, -0.0052198 ,  0.04034337, -0.05492509,  0.05276969,
       -0.00936191, -0.04249877,  0.02791705,  0.00306441, -0.06735141,
        0.01963284, -0.02593034, -0.0052198 ,  0.02377494,  0.00306441,
        0.09419076, -0.00936191, -0.03421455,  0.07348023, -0.01764613,
       -0.05078298, -0.08806194, -0.08391984, -0.02178823, -0.01350402,
        0.00720652, -0.02178823, -0.01350402,  0.04862759,  0.00720652,
        0.00720652, -0.01764613, -0.06735141, -0.05078298,  0.01963284,
       -0.03421455,  0.01963284, -0.02593034, -0.07149352,  0.01134862,
        0.01549073,  0.01963284,  0.00306441,  0.00306441,  0.01