In [82]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.datasets import load_wine
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [83]:
data=load_wine()
x=data.data
y=data.target

In [84]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [85]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [86]:
clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(x_train,y_train)

KNeighborsClassifier()

In [87]:
y_pred=clf.predict(x_test)
y_pred

array([1, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 2, 2, 2, 2, 0, 0, 1, 1, 0, 0, 2,
       0, 0, 2, 1, 0, 0, 1, 2, 2, 2])

In [88]:
clf.score(x_test,y_pred)

1.0

In [89]:
cross_val_score(clf,x_test,y_pred).mean()

0.7963636363636365

In [90]:
accuracy_score(y_test,y_pred)

0.6666666666666666

In [91]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.82      0.86        22
           1       0.68      0.71      0.70        21
           2       0.25      0.27      0.26        11

    accuracy                           0.67        54
   macro avg       0.61      0.60      0.61        54
weighted avg       0.68      0.67      0.67        54



In [92]:
print(confusion_matrix(y_test,y_pred))

[[18  0  4]
 [ 1 15  5]
 [ 1  7  3]]
