In [119]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.datasets import load_wine
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [120]:
data=load_wine()
x=data.data
y=data.target

In [131]:
df=pd.read_csv('../Datasets/score.csv')
df

Training  Testing  K  Accuracy  Avg_Accuracy
0       70.0     30.0  3       NaN           NaN
1        NaN      NaN  5       NaN           NaN
2        NaN      NaN  7       NaN           NaN
3        NaN      NaN  9       NaN           NaN
4       60.0     40.0  3       NaN           NaN
5        NaN      NaN  5       NaN           NaN
6        NaN      NaN  7       NaN           NaN
7        NaN      NaN  9       NaN           NaN
8       50.0     50.0  3       NaN           NaN
9        NaN      NaN  5       NaN           NaN
10       NaN      NaN  7       NaN           NaN
11       NaN      NaN  9       NaN           NaN
12      40.0     60.0  3       NaN           NaN
13       NaN      NaN  5       NaN           NaN
14       NaN      NaN  7       NaN           NaN
15       NaN      NaN  9       NaN           NaN
16      30.0     70.0  3       NaN           NaN
17       NaN      NaN  5       NaN           NaN
18       NaN      NaN  7       NaN           NaN
19       NaN      NaN  9       NaN           NaN

In [121]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [135]:
k=0
l=0
cavg=0
for j in range(0,len(df),4):
    h=3
    avg=0
    for i in range(3,10,2):
        x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=(h/10),random_state=0)
        clf=KNeighborsClassifier(n_neighbors=i)
        clf.fit(x_train,y_train)
        y_pred=clf.predict(x_test)
        acc=accuracy_score(y_test,y_pred)
        df.Accuracy[k]=acc
        k=k+1    
    h=h+1

0
3 3
5 3
7 3
9 3
4
3 3
5 3
7 3
9 3
8
3 3
5 3
7 3
9 3
12
3 3
5 3
7 3
9 3
16
3 3
5 3
7 3
9 3


C:\Users\CSE\AppData\Local\Temp\ipykernel_5548\350643322.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Accuracy[k]=acc
C:\Users\CSE\AppData\Local\Temp\ipykernel_5548\350643322.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Accuracy[k]=acc
C:\Users\CSE\AppData\Local\Temp\ipykernel_5548\350643322.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Accuracy[k]=acc
C:\Users\CSE\AppData\Local\Temp\ipykernel_5548\35064

In [158]:
 x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.7,random_state=0)
clf=KNeighborsClassifier(n_neighbors=7)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
acc=accuracy_score(y_test,y_pred)
acc

0.72

In [125]:
clf.score(x_test,y_pred)

1.0

In [126]:
cross_val_score(clf,x_test,y_pred).mean()

0.9178571428571429

In [127]:
accuracy_score(y_test,y_pred)

0.75

In [128]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.79      0.69      0.73        16
           2       0.38      0.50      0.43         6

    accuracy                           0.75        36
   macro avg       0.70      0.71      0.70        36
weighted avg       0.77      0.75      0.76        36



In [129]:
print(confusion_matrix(y_test,y_pred))

[[13  1  0]
 [ 0 11  5]
 [ 1  2  3]]
