In [119]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.datasets import load_wine
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [120]:
data=load_wine()
x=data.data
y=data.target

In [121]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [122]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [123]:
clf=KNeighborsClassifier(n_neighbors=9)
clf.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [124]:
y_pred=clf.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 2, 2, 1, 0, 0, 1, 0, 1, 0,
       1, 2, 2, 1, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0])

In [125]:
clf.score(x_test,y_pred)

1.0

In [126]:
cross_val_score(clf,x_test,y_pred).mean()

0.9178571428571429

In [127]:
accuracy_score(y_test,y_pred)

0.75

In [128]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.79      0.69      0.73        16
           2       0.38      0.50      0.43         6

    accuracy                           0.75        36
   macro avg       0.70      0.71      0.70        36
weighted avg       0.77      0.75      0.76        36



In [129]:
print(confusion_matrix(y_test,y_pred))

[[13  1  0]
 [ 0 11  5]
 [ 1  2  3]]
