In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score

In [2]:
weather=["Sunny","Sunny","Overcast","Rainy","Rainy","Rainy","Overcast","Sunny","Sunny","Rainy","Sunny","Overcast","Overcast","Rainy"]
temp=["Hot","Hot","Hot","Mild","Cool","Cool","Cool","Mild","Cool","Mild","Mild","Mild","Hot","Mild"]
play=["No","No","Yes","Yes","Yes","No","Yes","No","Yes","Yes","Yes","Yes","Yes","No"]

In [3]:
le=LabelEncoder()
w_encoded=le.fit_transform(weather)
w_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [4]:
t_encoded=le.fit_transform(temp)
t_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

In [5]:
p_encoded=le.fit_transform(play)
p_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [6]:
#converting the datasets to a simple np array
x_np=np.array([w_encoded,t_encoded])
x=x_np.transpose()
y=np.array(p_encoded).reshape(-1,1)
y.shape

(14, 1)

In [7]:
#use zip to combine
features=list(zip(w_encoded,t_encoded))
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [8]:
clf=KNeighborsClassifier()
clf.fit(x,y)

C:\Users\CSE\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [9]:
y_pred=clf.predict(x)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [10]:
clf.score(x,y_pred)

1.0

In [11]:
d=np.array([0,2]).reshape(1,-1)
# d
pred=clf.predict(d)
print(pred)

[1]


In [12]:
# cross_val_score(clf,x,y).mean()