In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.datasets import load_iris,load_diabetes

In [2]:
weather=["Sunny","Sunny","Overcast","Rainy","Rainy","Rainy","Overcast","Sunny","Sunny","Rainy","Sunny","Overcast","Overcast","Rainy"]
temp=["Hot","Hot","Hot","Mild","Cool","Cool","Cool","Mild","Cool","Mild","Mild","Mild","Hot","Mild"]
play=["No","No","Yes","Yes","Yes","No","Yes","No","Yes","Yes","Yes","Yes","Yes","No"]

In [3]:
le=LabelEncoder()

In [4]:
w_enc=le.fit_transform(weather)
t_enc=le.fit_transform(temp)
p_enc=le.fit_transform(play)

In [5]:
# x_np=np.array([w_enc,t_enc])
# x=x_np.transpose()
# y=np.array([p_enc])

In [6]:
# x_train,x_test,y_train,y_test=train_test_split(x,p_enc,test_size=0.3,random_state=1)

In [7]:
# clf=DecisionTreeClassifier(criterion="log_loss")
# clf.fit(x_train,y_train)

In [8]:
# y_pred=clf.predict(x_test)
# y_pred

In [9]:
# accuracy_score(y_test,y_pred)

In [10]:
# print(confusion_matrix(y_test,y_pred))

**Classification-:iris**

In [11]:
data=load_iris()
x=data.data
y=data.target

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [26]:
x_test.shape

(45, 4)

In [14]:
clf=DecisionTreeClassifier(criterion="entropy")
clf.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [15]:
y_pred=clf.predict(x_test)

In [16]:
accuracy_score(y_test,y_pred)

0.9555555555555556

In [17]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


**As a regressor for diabetes**

In [18]:
d=load_diabetes()
x1=d.data
y1=d.target

In [19]:
x_train_1,x_test_1,y_train_1,y_test_1=train_test_split(x1,y1,test_size=0.3,random_state=1)

In [20]:
x_train_1.shape

(309, 10)

In [21]:
reg=DecisionTreeRegressor()
reg.fit(x_train_1,y_train_1)

DecisionTreeRegressor()

In [25]:
x_test_1.shape

(133, 10)

In [24]:
y_pred_1=reg.predict(x_test_1)

In [23]:
reg.score(x_test_1,y_pred_1)

1.0