In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [4]:
df=pd.read_csv('../Datasets/Mall_Customers.csv')
df

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [5]:
x=df.iloc[:,2:4]
y=df.iloc[:,4]

In [13]:
x

Age  Annual Income (k$)
0     19                  15
1     21                  15
2     20                  16
3     23                  16
4     31                  17
..   ...                 ...
195   35                 120
196   45                 126
197   32                 126
198   32                 137
199   30                 137

[200 rows x 2 columns]

In [14]:
y

0      39
1      81
2       6
3      77
4      40
       ..
195    79
196    28
197    74
198    18
199    83
Name: Spending Score (1-100), Length: 200, dtype: int64

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.6)

In [9]:
reg2=LinearRegression()
reg2.fit(x_train,y_train)

LinearRegression()

In [10]:
y_pred=reg2.predict(x_test)

In [11]:
y_pred

array([47.02581419, 50.75673588, 39.19301035, 58.03832477, 43.95981166,
       46.9003215 , 47.93202054, 47.46123464, 37.92002413, 54.52511331,
       47.03760267, 37.69052543, 43.97160014, 50.34489239, 60.12739008,
       62.17348207, 52.38680378, 61.64375378, 53.51281065, 52.02002391,
       40.7918934 , 50.50366022, 46.39417018, 47.49660008, 42.79083146,
       63.35634103, 49.8151641 , 56.71818464, 49.25007038, 50.06823976,
       51.17066967, 56.39646839, 47.45153646, 58.487624  , 46.86286577,
       60.01368588, 60.74724562, 54.05223712, 57.8441915 , 58.63460335,
       44.91108163, 49.21679523, 55.52353719, 49.22858371, 60.35688879,
       37.79453145, 50.78240313, 48.32028707, 45.24667664, 45.7978916 ,
       38.31038096, 53.77767479, 60.21960763, 56.28276418, 43.78925535,
       51.94168514, 52.91444178, 54.55838845, 53.28540223, 50.50366022,
       49.30692248, 60.09411494, 52.16909356, 54.05223712, 42.18067411,
       48.72661297, 54.66030418, 47.86337995, 43.27131554, 59.50

In [15]:
reg2.score(x_test,y_pred)

1.0

In [21]:
x1=np.array([19,15]).reshape(1,-1)

array([[19, 15]])

In [27]:
reg2.predict(x1)

C:\Users\CSE\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([64.29791282])